name = "geodude-reco-consumer"
main = "src/index.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"

[[kv_namespaces]]
binding = "RECO_CACHE"
id = "placeholder-will-be-created"

[[queues.consumers]]
queue = "reco-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 2

[browser]
binding = "BROWSER"

[vars]
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_MODEL = "gpt-4o"

# Secrets (set via wrangler secret put):
# - OPENAI_API_KEY

