name = "geodude-reco-consumer"
main = "src/index.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

# All D1 databases, KV namespaces, queues, and other bindings removed
# This worker is now disabled

[vars]
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_MODEL = "gpt-4.5-turbo"