name = "geodude"
pages_build_output_dir = "apps/geodude/dist"
compatibility_date = "2025-08-01"

# Force cache invalidation and proper build from correct directory
[build]
command = "cd apps/geodude && rm -rf dist .vite && npm run build"
