name = "optiview"
main = "src/worker.ts"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "OPTIVIEW_DB"
database_name = "optiview_db"
database_id = "TBD"

[[kv_namespaces]]
binding = "AI_FINGERPRINTS"
id = "TBD"

[triggers]
# Uncomment to enable after testing
# crons = ["*/30 * * * *"]
