name = "optiview"
main = "src/worker.ts"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "OPTIVIEW_DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"

[[kv_namespaces]]
binding = "AI_FINGERPRINTS"
id = "571e1b9f739c4d0a9027b350cf091d20"

[triggers]
# Uncomment to enable after testing
# crons = ["*/30 * * * *"]

[env.production]
vars = { CSP_MODE = "production" }

[env.development]
vars = { CSP_MODE = "development" }

[env.dev]
vars = { CSP_MODE = "development" }
