name = "geodude-api"
main = "src/worker.js"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "OPTIVIEW_DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"

[[kv_namespaces]]
binding = "AI_FINGERPRINTS"
id = "571e1b9f739c4d0a9027b350cf091d20"

[triggers]
# Uncomment to enable after testing
# crons = ["*/30 * * * *"]

[env.production]
CSP_MODE = "production"
NODE_ENV = "production"
PUBLIC_APP_URL = "https://optiview.ai"
MAGIC_LINK_EXP_MIN = "15"
MAGIC_LINK_RPM_PER_IP = "10"
MAGIC_LINK_RPD_PER_EMAIL = "5"
INVITE_EXP_DAYS = "7"
EMAIL_FROM = "support@optiview.ai"
EMAIL_SENDER_NAME = "Optiview"

[env.development]
CSP_MODE = "development"
NODE_ENV = "development"
PUBLIC_APP_URL = "https://optiview.ai"
MAGIC_LINK_EXP_MIN = "15"
MAGIC_LINK_RPM_PER_IP = "10"
MAGIC_LINK_RPD_PER_EMAIL = "50"
INVITE_EXP_DAYS = "7"
EMAIL_FROM = "support@optiview.ai"
EMAIL_SENDER_NAME = "Optiview"
TEST_MODE = "1"

[env.dev]
CSP_MODE = "development"
NODE_ENV = "development"
PUBLIC_APP_URL = "https://optiview.ai"
MAGIC_LINK_EXP_MIN = "15"
MAGIC_LINK_RPM_PER_IP = "10"
MAGIC_LINK_RPD_PER_EMAIL = "50"
INVITE_EXP_DAYS = "7"
EMAIL_FROM = "support@optiview.ai"
EMAIL_SENDER_NAME = "Optiview"
TEST_MODE = "1"
