name = "geodude-api"
compatibility_date = "2025-08-01"

# Database binding
[[d1_databases]]
binding = "OPTIVIEW_DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"

# KV Namespaces
[[kv_namespaces]]
binding = "AI_FINGERPRINTS"
id = "571e1b9f739c4d0a9027b350cf091d20"

[[kv_namespaces]]
binding = "CACHE"
id = "351597e3c9e94f908fb256c50c8fe5c8"

[[kv_namespaces]]
binding = "RL"
id = "828d43c4d01a4da59e1eb457a118b6f1"

[[kv_namespaces]]
binding = "METRICS"
id = "cfde18666cfc4904b64f63259f62e09f"
