name = "geodude-api"
main = "src/index.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"
migrations_dir = "../../db/migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "29edf1f05bde42c09b7afa8e128b7066"

[[kv_namespaces]]
binding = "RECO_CACHE"
id = "6f25c753a8734206bc07c1418423ca1b"

[[kv_namespaces]]
binding = "PROMPT_PACKS"
id = "d1fe329042554316af448f986b3a7e0d"

[[kv_namespaces]]
binding = "ASSISTANT_SCHEDULES"
id = "05aa79aa479d44f7a599735e03ad2a78"

[[kv_namespaces]]
binding = "HEURISTICS"
id = "e037590f3aa9494cbd4d30d5fd6bc333"

# [[kv_namespaces]]
# binding = "KV_VI_CACHE"
# id = "f148590f3aa9494cbd4d30d5fd6bc334"

# [[kv_namespaces]]
# binding = "KV_VI_RULES"
# id = "f248590f3aa9494cbd4d30d5fd6bc335"

# [[kv_namespaces]]
# binding = "KV_VI_SEEDS"
# id = "f348590f3aa9494cbd4d30d5fd6bc336"

[[queues.producers]]
binding = "RECO_PRODUCER"
queue = "reco-queue"

[[r2_buckets]]
binding = "R2_BACKUPS"
bucket_name = "geodude-backups"

[vars]
USER_AGENT = "OptiviewAuditBot/1.0 (+https://www.optiview.ai)"
AUDIT_MAX_PAGES = "100"
AUDIT_DAILY_LIMIT = "20"
HASH_SALT = "prod_salt_6bd61859686eebd3e0caa31f2192ac83"
BRAVE_SEARCH_ENDPOINT = "https://api.search.brave.com/res/v1/web/search"
CITATIONS_MAX_PER_QUERY = "5"
CITATIONS_DAILY_BUDGET = "200"
FROM_EMAIL = "Optiview <no-reply@optiview.ai>"
RENDER_MODE = "browser"
RENDER_TIMEOUT_MS = "8000"
RENDER_MAX_PAGES = "100"
# Phase F+ Brave AI Configuration
BRAVE_MAX_QUERIES = "50"            # Soft cap per audit (was 20)
BRAVE_AI_HARD_CAP = "100"           # Absolute max
BRAVE_TIMEOUT_MS = "7000"           # Per-query timeout (7s)
BRAVE_MAX_CONCURRENT = "2"          # Max concurrent requests
BRAVE_RETRY_5XX = "1"               # Retry once on 5xx errors
BRAVE_DIAGNOSTICS = "1"             # Enable per-query diagnostics
BRAVE_AI_ENABLE_COMPARE = "false"   # Enable competitor comparison queries
BRAVE_QUERY_STRATEGY = "smart"      # smart | basic | aggressive
# Phase H: UI Scrape Adapters (Spike)
LLM_UI_ENABLED = "false"            # Master flag for UI scraping
LLM_UI_MAX_QUERIES = "10"           # Max UI queries per audit
LLM_UI_TIMEOUT_MS = "30000"         # Per-query timeout (longer for UI rendering)
LLM_UI_PROVIDERS = "perplexity"     # Comma-separated: perplexity,you,bing
ENABLE_PERPLEXITY = "false"
ENABLE_YOUCOM = "false"
ENABLE_HEADLESS_PROVIDERS = "false"
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_MODEL = "gpt-4o"
RECO_ALLOWED_DOMAINS = ""
BRAVE_QPS = "3"
TAVILY_QPS = "3"
PPLX_QPS = "2"
PROVIDER_CACHE_TTL = "86400"
ENABLE_MULTI_PROVIDER = "1"
FAQ_ALLOWLIST = "/faq,/support/faq,/help/faq,/frequently-asked-questions"

# Phase Next: Assistant Visibility & E-E-A-T
FEATURE_ASSISTANT_VISIBILITY = "true"
FEATURE_EEAT_SCORING = "false"
BROWSER_CLUSTER_MAX = "2"
FETCH_TIMEOUT_MS = "20000"
VISIBILITY_RATE_LIMIT_PER_PROJECT = "30"
ALLOWED_ANSWER_ENGINES = "perplexity,claude-web"
GA4_REGEX_SNIPPET_URL = ""

# Live Connectors (Phase 4 - Sprint 1)
FEATURE_VIS_PERPLEXITY = "true"
FEATURE_VIS_CHATGPT = "true"
FEATURE_VIS_CLAUDE = "true"
VIS_CONNECT_TIMEOUT_MS = "15000"
VIS_CONNECT_RETRIES = "2"
VIS_RATE_PER_PROJECT = "20"
VIS_DAILY_COST_CAP_USD = "10"
# Phase 5 Analytics
FEATURE_PHASE5_ANALYTICS = "true"

# Visibility Intelligence (VI) Configuration
USE_LIVE_VISIBILITY = "true"
VI_SOURCES = '["chatgpt","perplexity","claude"]'
VI_REFRESH_CRON = "0 */6 * * *"
VI_MAX_INTENTS = "120"
VI_INTENT_TIMEOUT_MS = "25000"
VI_CONNECTOR_TIMEOUT_MS = "35000"
VI_CACHE_TTL_SEC = "172800"
VI_RECENCY_HOURS = "6"

[browser]
binding = "BROWSER"

[observability]
enabled = true

[observability.logs]
enabled = true

# Secrets (set via wrangler secret put):
# - BRAVE_SEARCH (already set in Cloudflare)
# - BRAVE_SEARCH_AI (already set in Cloudflare)
# - RESEND_KEY (already set in Cloudflare)
# - OPENAI_API_KEY (required for content recommendations)

[triggers]
crons = ["0 6 * * 1", "0 3 * * *", "*/5 * * * *", "0 */6 * * *"]

