name = "geodude-api"
main = "src/index.ts"
compatibility_date = "2024-11-20"

[[d1_databases]]
binding = "DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "29edf1f05bde42c09b7afa8e128b7066"

[vars]
USER_AGENT = "OptiviewAuditBot/1.0 (+https://www.optiview.ai)"
AUDIT_MAX_PAGES = "30"
AUDIT_DAILY_LIMIT = "10"
HASH_SALT = "prod_salt_6bd61859686eebd3e0caa31f2192ac83"
BRAVE_SEARCH_ENDPOINT = "https://api.search.brave.com/res/v1/web/search"
CITATIONS_MAX_PER_QUERY = "5"
FROM_EMAIL = "Optiview <no-reply@optiview.ai>"

# Secrets (set via wrangler secret put):
# - BRAVE_SEARCH (already set in Cloudflare)
# - RESEND_KEY (already set in Cloudflare)

[triggers]
crons = ["0 6 * * 1"]

