# Staging configuration for Phase Next testing
name = "geodude-api-staging"
main = "src/index.ts"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "optiview_db"
database_id = "975fb94d-9fac-4fd9-b8e2-41444f488334"
migrations_dir = "../../db/migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "29edf1f05bde42c09b7afa8e128b7066"

[[kv_namespaces]]
binding = "RECO_CACHE"
id = "6f25c753a8734206bc07c1418423ca1b"

[[kv_namespaces]]
binding = "PROMPT_PACKS"
id = "prompt-packs-namespace"

[[kv_namespaces]]
binding = "ASSISTANT_SCHEDULES"
id = "assistant-schedules-namespace"

[[kv_namespaces]]
binding = "HEURISTICS"
id = "heuristics-namespace"

[[queues.producers]]
binding = "RECO_PRODUCER"
queue = "reco-queue"

[[r2_buckets]]
binding = "R2_BACKUPS"
bucket_name = "geodude-backups"

[vars]
USER_AGENT = "OptiviewAuditBot/1.0 (+https://www.optiview.ai)"
AUDIT_MAX_PAGES = "100"
AUDIT_DAILY_LIMIT = "20"
HASH_SALT = "prod_salt_6bd61859686eebd3e0caa31f2192ac83"
BRAVE_SEARCH_ENDPOINT = "https://api.search.brave.com/res/v1/web/search"
CITATIONS_MAX_PER_QUERY = "5"
CITATIONS_DAILY_BUDGET = "200"
FROM_EMAIL = "Optiview <no-reply@optiview.ai>"
RENDER_MODE = "browser"
RENDER_TIMEOUT_MS = "8000"
RENDER_MAX_PAGES = "100"
# Phase F+ Brave AI Configuration
BRAVE_MAX_QUERIES = "50"
BRAVE_AI_HARD_CAP = "100"
BRAVE_TIMEOUT_MS = "7000"
BRAVE_MAX_CONCURRENT = "2"
BRAVE_RETRY_5XX = "1"
BRAVE_DIAGNOSTICS = "1"
BRAVE_AI_ENABLE_COMPARE = "false"
BRAVE_QUERY_STRATEGY = "smart"
# Phase H: UI Scrape Adapters (Spike)
LLM_UI_ENABLED = "false"
LLM_UI_MAX_QUERIES = "10"
LLM_UI_TIMEOUT_MS = "30000"
LLM_UI_PROVIDERS = "perplexity"
ENABLE_PERPLEXITY = "false"
ENABLE_YOUCOM = "false"
ENABLE_HEADLESS_PROVIDERS = "false"
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_MODEL = "gpt-4o"
RECO_ALLOWED_DOMAINS = ""
BRAVE_QPS = "3"
TAVILY_QPS = "3"
PPLX_QPS = "2"
PROVIDER_CACHE_TTL = "86400"
ENABLE_MULTI_PROVIDER = "1"
FAQ_ALLOWLIST = "/faq,/support/faq,/help/faq,/frequently-asked-questions"

# Phase Next: Assistant Visibility & E-E-A-T - STAGING ENABLED
FEATURE_ASSISTANT_VISIBILITY = "true"
FEATURE_EEAT_SCORING = "true"
BROWSER_CLUSTER_MAX = "1"
FETCH_TIMEOUT_MS = "20000"
VISIBILITY_RATE_LIMIT_PER_PROJECT = "20"
ALLOWED_ANSWER_ENGINES = "perplexity,claude-web"
GA4_REGEX_SNIPPET_URL = ""

[browser]
binding = "BROWSER"

[observability]
enabled = true

[observability.logs]
enabled = true

[triggers]
crons = ["0 6 * * 1", "0 3 * * *"]
