name: prune-merged-branches
on:
  schedule: [{ cron: "0 7 * * 1" }]  # Mondays 07:00 UTC
  workflow_dispatch: {}
jobs:
  prune:
    runs-on: ubuntu-latest
    permissions: { contents: write, pull-requests: read }
    steps:
      - uses: actions/checkout@v4
      - name: Delete remote branches merged into main (exclude protected)
        run: |
          git fetch --all --prune
          for b in $(git branch -r --merged origin/main | sed 's|origin/||'); do
            case "$b" in main|HEAD|release/*) continue ;; esac
            echo "Deleting $b"; git push origin --delete "$b" || true
          done

