name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/app build
      - run: pnpm -C packages/api-worker build || true
      
      - name: API smoke - citations shape
        run: |
          # Test that citations endpoint returns {items:[]} shape
          RESPONSE=$(curl -s https://api.optiview.ai/v1/audits/aud_1760034537103_bx07fbfu2/citations)
          echo "$RESPONSE" | jq -e 'has("items")' || (echo "❌ Citations endpoint missing 'items' key" && exit 1)
          echo "✅ Citations endpoint returns correct shape"
      
      - name: API smoke - status
        run: |
          # Test that status endpoint returns ok
          curl -s https://api.optiview.ai/status | jq -e '.status=="ok"' || (echo "❌ Status endpoint not OK" && exit 1)
          echo "✅ Status endpoint healthy"

