name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/app build
      - run: pnpm -C packages/api-worker build || true
      
      - name: Audit Worker API smoke test
        run: |
          # Test that audit worker endpoints are responding correctly
          echo "Testing audit worker endpoints..."
          
          # Test seed rules endpoint
          RESPONSE=$(curl -s https://optiview-audit-worker.kevin-mcgovern.workers.dev/api/admin/seed-rules)
          echo "$RESPONSE" | jq -e 'has("status") and .status=="seeded"' || (echo "❌ Seed rules endpoint not working" && exit 1)
          echo "✅ Seed rules endpoint working"
          
          # Test audit creation endpoint
          AUDIT_RESPONSE=$(curl -s -X POST https://optiview-audit-worker.kevin-mcgovern.workers.dev/api/audits \
            -H "Content-Type: application/json" \
            -d '{"project_id":"ci_test","root_url":"https://example.com","max_pages":1}')
          echo "$AUDIT_RESPONSE" | jq -e 'has("audit_id") and has("status")' || (echo "❌ Audit creation endpoint not working" && exit 1)
          echo "✅ Audit creation endpoint working"

