name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Do NOT pass "version" here; the action will read packageManager from package.json
      - uses: pnpm/action-setup@v3
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w run typecheck
