name: deploy-app
on:
  workflow_dispatch: {}  # Manual trigger only
  # Disabled auto-deploy since we're using manual wrangler pages deploy
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'apps/app/**'
  #     - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build dashboard
        run: pnpm -C apps/app build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/app/dist --project-name=geodude-app --branch=main

# NOTE: Add these secrets to GitHub:
# - CLOUDFLARE_API_TOKEN (Cloudflare dashboard → My Profile → API Tokens → Create Token)
# - CLOUDFLARE_ACCOUNT_ID (Cloudflare dashboard → Workers & Pages → Account ID)

