name = "geodude-collector"
main = "src/index.ts"
compatibility_date = "2024-11-20"

# All D1 databases and bindings removed
# This worker is now disabled

[vars]
HASH_SALT = "prod_salt_6bd61859686eebd3e0caa31f2192ac83"